fix(indicators): only SetAlpha when 0 or higher
Nevcairiel/ShadowedUnitFrames pull request #27
Opened 2022-10-27 03:34 UTC by seanpeters86

I'm not sure on root cause but this fixes this from constantly spewing errors:

```
119883x ...ace/AddOns/ShadowedUnitFrames/modules/indicators.lua:276: bad argument #1 to 'SetAlpha' (Usage: self:SetAlpha(alpha))
[string "=[C]"]: in function `SetAlpha'
[string "@Interface/AddOns/ShadowedUnitFrames/modules/indicators.lua"]:276: in function <...ace/AddOns/ShadowedUnitFrames/modules/indicators.lua:270>

Locals:
(*temporary) = Texture {
enabled = true
status = "ready"
0 = <userdata>
}
(*temporary) = -0.001000
```

Basically at some point everything goes haywire and it keeps trying to set this value to a negative number. This seems to resolve it for me

2022-10-29 17:19 UTC, Topping commented on modules/indicators.lua
> +					if ( fadeFrameAlpha > 0 ) then
Can collapse with below if statement to clean up a bit
```
if (fadeFrameAlpha > 0 ) then
  fadeFrame:SetAlpha(fadeFrameAlpha)
else 
  f.fadeList[fadeFrame] = nil
  fadeFrame:Hide()
end
```

2022-10-29 17:21 UTC, Topping requested changes
Line 247-249 has similar indications if a number that is less than zero.

Line 249 checks if self.timeLeft is less than zero, implying that self.timeLeft CAN be less than zero.

On line 247 this could result in the same error as you fixed below. Recommend also guarding here in your changes.

2022-10-30 08:55 UTC, rionshin approved these changes

2022-10-31 16:16 UTC, s0ftcorn commented on modules/indicators.lua
> +					if ( fadeFrameAlpha > 0 ) then
Just modified the files manually and this fixes the errors on ready checks.

2022-11-04 04:22 UTC, closed without merging