Combined fixes for TWW
Nevcairiel/ShadowedUnitFrames pull request #49
Opened 2024-07-14 02:11 UTC by nulian

Combined the fixes for TWW of several people and fixed some things myself got it running and in options.
Though no extensive testing done with it yet.

Use what you want from it.

2024-07-14 02:15 UTC, nulian commented
Others are 
https://github.com/Hyphie24/ShadowedUnitFrames

And this MR to replace deprecated unitframes

https://github.com/Nevcairiel/ShadowedUnitFrames/pull/48

2024-07-20 20:09 UTC, Hyphie24 commented
Using both yours and mine, can load and move frames, but frames get "stuck" on screen when you go to relock them (this was the issue I was getting)

did some digging & I fixed it (temporarily) Line 482 of Layout.lua

Without digging fully into why it's dividing by 0 with the error it's giving, but just commenting out that line fixes that issue for now.

2024-07-24 07:12 UTC, argium requested changes

2024-07-24 07:12 UTC, argium commented on modules/range.lua
> +local function isUsable(key)
There are a lot of references to `GetSpellInfo` in the options addon. If Blizzard has standardised everything to the table structure, then the correct fix would be to update all business logic to use the new structure, and then handle migrating the existing spell IDs that have been saved in the profile.

config.lua lines 499-529

2024-08-13 22:09 UTC, nulian commented
Closing because most of these bugs are fixed in latest version

2024-08-13 22:09 UTC, closed without merging